### ISSUE TITLE
Webpack errors

### ISSUE THREAD

**Issue by Ofer-Gal** [yohanb/spsave-webpack-plugin#3]
After configuring like instarctions
I get
Error: 'output.filename' is required, either in config file or as --output-filename
    at processOptions (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:507:11)
    at processConfiguredOptions (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:150:4)
    at module.exports (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:112:10)
    at yargs.parse (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\Users\ofer\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3

**Comment by s-KaiNet** [comment]
Can you please post your `webpack.config` file?

**Comment by Ofer-Gal** [comment]
Here it is
[webpack.config.zip](https://github.com/yohanb/spsave-webpack-plugin/files/1290543/webpack.config.zip)
Hope you can help
Thank you

**Comment by s-KaiNet** [comment]
You have a few issues with your `webpack.config.js`, mainly because readme is a bit outdated, so I've updated README file with minimal valid configuration sample.   
Here are the changes you need to add.   
First of all, since that's `.js` file, you need to export something from your javascript file. You need to add  
```javascript
module.exports = webpackConfig;
```  
at the end of your file.   
[`entry`](https://webpack.js.org/configuration/entry-context/#entry) option should to be relative path:  
```javascript
entry: './index.js'
```  
from the other hand [`path`](https://webpack.js.org/configuration/output/#output-path) should to be absolute:  
```javascript
var path = require('path');

var SPSaveWebpackPlugin = require('spsave-webpack-plugin');
var root = path.join.bind(path, path.resolve(__dirname));
.....
path: root('dist'), // <-- abs path relative to root directory
```     
Also please update pluging to the latest version, because I've found one bug while testing and fix it in a newer version :)

**Comment by Ofer-Gal** [comment]
Thank you much. works fine now. When I got it from https://www.npmjs.com/package/spsave-webpack-plugin it did not have the same explanation as in https://github.com/yohanb/spsave-webpack-plugin 
I have seen you updated it.
Thank you again.
